version: '3.8'

services:
  # Backend API
  backend:
    image: node:18-alpine
    container_name: mirg-backend
    working_dir: /app
    ports:
      - "3120:3100"
    environment:
      NODE_ENV: production
      PORT: 3100
      WEAVIATE_URL: http://weaviate:8080
    volumes:
      - ./backend-app:/app
    command: node server.js
    depends_on:
      - weaviate
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3100/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Frontend
  frontend:
    image: nginx:alpine
    container_name: mirg-frontend  
    ports:
      - "3010:80"
    volumes:
      - ./frontend-app:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped

  # Weaviate Vector Database
  weaviate:
    image: semitechnologies/weaviate:1.25.0
    container_name: mirg-weaviate
    ports:
      - "8091:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
      STANDALONE_MODE: 'true'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  weaviate_data:
    driver: local

networks:
  default:
    name: mirg-network