version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.portainer
    container_name: mirg-backend
    ports:
      - "3121:3100"
    environment:
      NODE_ENV: production
      PORT: 3100
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.portainer
    container_name: mirg-frontend
    ports:
      - "3011:80"
    restart: unless-stopped
    depends_on:
      - backend