#!/bin/bash

# MIRG Stack Manual Deployment Helper
# This script provides the deployment content and instructions for manual Portainer deployment

echo "🚀 MIRG Stack - Manual Portainer Deployment"
echo "============================================="
echo ""
echo "📋 DEPLOYMENT STEPS:"
echo ""
echo "1. Open Portainer: http://192.168.86.97:9000"
echo "2. Navigate to: Stacks → + Add stack" 
echo "3. Stack name: mirg"
echo "4. Select 'Web editor' tab"
echo "5. Copy the compose content below"
echo "6. Click 'Deploy the stack'"
echo ""
echo "⏱️  Expected deployment time: 4-6 minutes"
echo ""
echo "📄 DOCKER COMPOSE CONTENT TO COPY:"
echo "=========================================="
echo ""
cat docker-compose.portainer-fixed.yml
echo ""
echo "=========================================="
echo ""
echo "🌐 EXPECTED SERVICE URLS AFTER DEPLOYMENT:"
echo ""
echo "- Frontend:     http://192.168.86.97:3011"
echo "- Backend API:  http://192.168.86.97:3121"
echo "- Health Check: http://192.168.86.97:3121/health"
echo "- Weaviate DB:  http://192.168.86.97:8093"
echo "- Weaviate API: http://192.168.86.97:8093/v1/.well-known/ready"
echo ""
echo "✅ VERIFICATION COMMAND AFTER DEPLOYMENT:"
echo "./verify-deployment-final.sh"
echo ""
echo "🔧 TROUBLESHOOTING:"
echo "- Check Portainer stack logs if deployment fails"
echo "- Verify NAS paths exist: /volume1/docker/projects/rules-generator/"
echo "- Ensure ports 3011, 3121, 8093 are available"
echo "- Allow 2-3 minutes for backend TypeScript compilation"
echo ""
echo "📖 Full guide: PORTAINER_MANUAL_DEPLOYMENT_GUIDE.md"
echo ""