version: '3.8'
services:
  weaviate:
    image: semitechnologies/weaviate:1.25.0
    container_name: rules-weaviate
    ports:
      - "8091:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
      CLUSTER_ADVERTISE_ADDR: '127.0.0.1'
      CLUSTER_GOSSIP_BIND_PORT: '7946'
      CLUSTER_DATA_BIND_PORT: '7947'
      STANDALONE_MODE: 'true'
      DISABLE_GOSSIP: 'true'
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - rules-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/v1/.well-known/ready"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.portainer
    container_name: rules-backend
    ports:
      - "3120:3100"
    environment:
      - NODE_ENV=development
      - WEAVIATE_URL=http://weaviate:8080
      - PORT=3100
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      weaviate:
        condition: service_healthy
    networks:
      - rules-network
    restart: unless-stopped
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.portainer
    container_name: rules-frontend
    ports:
      - "3010:80"
    environment:
      - VITE_API_URL=http://192.168.86.97:3120
    depends_on:
      - backend
    networks:
      - rules-network
    restart: unless-stopped

volumes:
  weaviate_data:

networks:
  rules-network:
    driver: bridge